repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks: [ {id: black} ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks: [ {id: ruff, args: ["--fix"]} ]
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.5
    hooks:
      - id: nbqa-black
      - id: nbqa-ruff
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks: [ {id: nbstripout} ]
